### ISSUE TITLE
Arrange of complex scheme

### ISSUE THREAD

**Issue by Ni55aN** [retejs/auto-arrange-plugin#1]
Arrange multiple output nodes (multiple depth)

**Comment by Ni55aN** [comment]
v0.2.0 is published, but it can allocate nodes based on table columns 

![opera snapshot_2018-12-09_155818_127 0 0 1](https://user-images.githubusercontent.com/8259641/49698382-8a2df280-fbcb-11e8-8333-471e2c1b4532.png)

I think we need something like this 

![opera snapshot_2018-12-09_155844_127 0 0 1](https://user-images.githubusercontent.com/8259641/49698384-8d28e300-fbcb-11e8-80a2-1196cf48440b.png)

**Comment by Githamza** [comment]
Thanks , nice work , 
but I don't found any documentation .

To make the auto arrange work I juste need to use the `editor.use(()` method ?

**Comment by Ni55aN** [comment]
@Githamza `editor.arrange(node);`

**Comment by Githamza** [comment]
> @Githamza `editor.arrange(node);`

it's working but I get this warning in compilator

`ERROR in src/app/rete/rete.component.ts(140,14): error TS2339: Property 'arrange' does not exist on type 'NodeEditor'.`

**Comment by Ni55aN** [comment]
@Githamza for TS you can define something like

```ts
declare module 'rete/types/editor' {
  interface NodeEditor {
    arrange(node?: Node);
  }
}
```

**Comment by Ni55aN** [comment]
By the way, I'm planning to change method calling to an event triggering

**Comment by Ni55aN** [comment]
@Githamza starting from v0.3.0 you should to trigger `arrange` event instead of calling the `arrange` method

**Comment by seveibar** [comment]
I'd also like to see more complex schemes supported, I'm also interested in contributing but may not be able to immediately (will PR if possible)

Below is an example of another complex scheme I'd like supported...

![image](https://user-images.githubusercontent.com/1910070/60349453-9f177b00-998f-11e9-9ebd-c496bcc79897.png)

This autoarranges as show below currently...

![image](https://user-images.githubusercontent.com/1910070/60349621-f7e71380-998f-11e9-8dc5-b4964556ed33.png)

**Comment by Ni55aN** [comment]
@seveibar Rete core doesn't support a recurrent nodes

**Comment by Ni55aN** [comment]
https://github.com/retejs/auto-arrange-plugin/pull/5#issuecomment-538668864
