### ISSUE TITLE
Arrange should take care of the frame comment

### ISSUE THREAD

**Issue by Armaldio** [retejs/auto-arrange-plugin#2]
If your nodes are wrapped in a frame comment, the comment frame is left at its original position when autoArranging

**Comment by Ni55aN** [comment]
In `rete-auto-arrange-plugin@0.2.1` fixed translating a node (via node view)
In `rete-comment-plugin@0.4.0` you can trigger `syncframes` event after call `editor.arrange()`

**Comment by Ni55aN** [comment]
https://github.com/retejs/comment-plugin/issues/5
