### ISSUE TITLE
TypeError: Cannot read property 'outputs' of undefined

### ISSUE THREAD

**Issue by seveibar** [retejs/auto-arrange-plugin#3]
Here's the issue reproduced on [CodeSandbox](https://codesandbox.io/s/cn148) [(browser view)](https://cn148.codesandbox.io/)

AutoArrange throws the type error:
`TypeError: Cannot read property 'outputs' of undefined`

Relevant dependencies:
```
    "rete": "1.2.2",
    "rete-area-plugin": "^0.2.1",
    "rete-auto-arrange-plugin": "^0.3.0",
    "rete-connection-plugin": "0.7.0",
    "rete-context-menu-plugin": "^0.3.7",
    "rete-react-render-plugin": "^0.1.2",
```

**Comment by seveibar** [comment]
This seems to happen before the components have "mounted". `editor.nodes` is an empty array at that point in time. Using `setTimeout` or waiting for `editor.nodes` to be populated is a quick fix.

The expected behavior is probably to execute the arrange after mounting. This issue may also be specific to react.

**Comment by Ni55aN** [comment]
```js
await editor.fromJSON({ /// ...
/// 
editor.trigger("arrange", { node: editor.nodes[0] });
