### ISSUE TITLE
Licensing incompatibility with elkjs

### ISSUE THREAD

**Issue by Sytten** [retejs/auto-arrange-plugin#32]
Hi there!

We are currently in the process of using rete in our commercial application and I was reviewing the list of dependencies it added to our tree. I saw that this plugin uses [elkjs](https://github.com/kieler/elkjs) which uses the EPL 2.0 license (https://github.com/kieler/elkjs/blob/master/LICENSE.md). I am not a lawyer but from my reading this license is not compatible with an MIT license as a derivative and it just creates unnecessary licensing issues for commercial projects. In theory if you only use the lib and don't modify it, only it's not considered derivative but then a bundler that minifies the code and mix it with other dependencies could be considered a derivative work.

I think it would be best to use another dependency with a more permissive license since the author is unwilling to dual license it (https://github.com/kieler/elkjs/issues/158).

Thanks!

**Comment by Ni55aN** [comment]
At this point, I can only fix the license to make it compatible with Elk.js

> unnecessary licensing issues for commercial projects

Perhaps, but I haven't come across any alternatives with the same feature set, like port-based constraints

P.S. Regarding commercial use, please take note that certain Rete.js plugins are presently not permitted for such purposes (I've been considering dual licensing, but I haven't implemented it yet)

**Comment by Ni55aN** [comment]
I'm at a loss 🙆‍♂️ [mermaid/package.json#L46-L69](https://github.com/mermaid-js/mermaid/blob/develop/packages/mermaid/package.json#L46-L69)

I need to delve into this

**Comment by Sytten** [comment]
I might have been a bit hasty on my previous comment, I think you can keep MIT but you should probably put a warning about the EPL dependency in the README. I ideally the dagree PR gets done so it's an alternative backend that is MIT.
I mentioned mermaid to the elkjs dev, but he really can't change anything because the Java ELK code is under EPL too so it would not even matter if elkjs is dual-license.

I read a bit about the google policies for OSS (https://opensource.google/documentation/reference/thirdparty/licenses) and it looks like a bundler would not be considered a violation of the EPL. Though the ELKJS depends on sources of ELK which are not present in the same repo so it makes is complicated to respect the license.

But nevertheless the elkjs is a big java GWT dep of 1.5MB so it's not great.

**Comment by Sytten** [comment]
Regarding the plugin use in commercial, @Ni55aN I would very much like to know which one we can use. Considering they are MIT and the doc is vague about it.

**Comment by Ni55aN** [comment]
While I was selecting a library for layout design, I looked into dagre as one of the options. Although it might be suitable for basic scenarios, it lacks port alignment (and  support for nested nodes, as I remember), so I decided not to rely on it.

Right, 1.5MB is a big bundle, but it can be used using lazy loading. Unfortunately I did not find other alternatives

**Comment by Ni55aN** [comment]
@Sytten I replied via email regarding plugins

**Comment by Sytten** [comment]
Yeah I did look around a bit, but there is not much available apart from elkjs. I guess someone needs to reimplement the algo in typescript or rust/wasm :D
I know dagre is getting going again (https://github.com/dagrejs/dagre/issues/352) so maybe it will be a viable alternative at some point.
We will use it as-is for now, thanks for the follow-up!
