### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by petrkrejci1** [retejs/auto-arrange-plugin#4]
Hi,
I would like to report a bug I have just found. Even though the graph does not have any recursive connection I am getting a following error:
> auto-arrange.js:10 Uncaught RangeError: Maximum call stack size exceeded
>     at String.concat (<anonymous>)
>     at n.value (auto-arrange.js:10)
>     at n.value (auto-arrange.js:26)
>     at auto-arrange.js:26
>     at Array.map (<anonymous>)
>     at n.value (auto-arrange.js:26)
>     at auto-arrange.js:26
>     at Array.map (<anonymous>)
>     at n.value (auto-arrange.js:26)
>     at auto-arrange.js:26

Here is the graph that caused this bug:
![image](https://user-images.githubusercontent.com/31248142/59957512-1c08a780-94ed-11e9-9cde-5a12a6893128.png)

I am using native arrange-plugin without any changes and I would really appreciate any suggestion that might solve this issue.

Cheers,
Petr

**Comment by Ni55aN** [comment]
Hi, current alghorithm based on table and has such a problems. Ideally, it should be replaced with something more flexible, but I still haven't figured it out.

**Comment by petrkrejci1** [comment]
I see, thank you for your answer anyway.

**Comment by Ni55aN** [comment]
v0.4.0 has fixes for this bug

**Comment by petrkrejci1** [comment]
Hi, Vitaliy,
I have received your update to v0.4.0 and just finished testing of several different types of graphs and it works perfectly without any issue.

Thank you so much for the fix and for your effort.

Petr
