### ISSUE TITLE
AutoArrange cut on top of window

### ISSUE THREAD

**Issue by Githamza** [retejs/auto-arrange-plugin#7]
I would auto arrange nodes generated automatically

I'm using this config

`editor.use(AutoArrangePlugin, { margin: { x: 50, y: 50 }, depth: 0 })`

The problem is that my components get clipped ouf of the container.

Is there a way to adapte editor the it's container ?

Here the issue
![Capture d’écran 2019-09-13 à 00 50 27](https://user-images.githubusercontent.com/11578288/64859628-15d92180-d62b-11e9-8ae3-d020912a3870.png)

**Comment by Ni55aN** [comment]
>  my components get clipped ouf of the container

Is it just outside of viewport or you cannot  see it anymore after translating area? Could you provide a screenshot/video with the devtools inspector?

**Comment by Githamza** [comment]
Yes I can see it when I move the editor or unzoom

**Comment by Ni55aN** [comment]
Then I don’t understand what the problem is, as this is the expected behavior. If you need to place all nodes in the viewport, use `area plugin`

**Comment by Githamza** [comment]
How can I use `Area plugin` to fit the container? 
`editor.use(AreaPlugin, { What params to use ?});`  Can't find documentation about

Should I put it before `editor.fromJson()` or after ?

**Comment by Ni55aN** [comment]
```js
import { zoomAt } from 'rete-area-plugin';

await editor.fromJSON(data);
zoomAt(editor);
```

**Comment by Githamza** [comment]
zoomAt function is not found `export 'zoomAt' was not found in 'rete-area-plugin'`
I'm using 0.2.1 version

**Comment by Ni55aN** [comment]
Sorry, the plugin has `zoomAt ` in the default export

```js
import AreaPlugin from 'rete-area-plugin';

await editor.fromJSON(data);
AreaPlugin.zoomAt(editor);
```

**Comment by Githamza** [comment]
You rock ! that's working
