### ISSUE TITLE
AutoArrange module cause overflow

### ISSUE THREAD

**Issue by Githamza** [retejs/auto-arrange-plugin#8]
I would auto arrange nodes generated automatically

I'm using this config

` editor.use(AutoArrangePlugin, { margin: { x: 50, y: 50 }, depth: 0 })`

The problem is that my components get clipped ouf of the container.

Is there a way to adapte  editor the it's container ?

Here the issue
![Capture d’écran 2019-09-13 à 00 50 27](https://user-images.githubusercontent.com/11578288/64858257-2c7d7980-d627-11e9-9161-131854f42db2.png)

**Comment by Ni55aN** [comment]
https://github.com/retejs/auto-arrange-plugin/issues/7
